### ISSUE TITLE
Is there any workaround about this?

### ISSUE THREAD

**Issue by epitomz** [havran/angular-APP_INITIALIZER-bug#1]
Hey! 

I have an SSR app and the auth guard is triggered before the `APP_INITIALIZER` promise has been completed (because of the `initialNavigation = 'enabled`

Any workaround about this bug?

Cheers,
Antonin

**Comment by havran** [comment]
Hi, i try solve this problem only for configuration which i need use inside guard.

I solve my problem by reading configuration in main.ts:

https://github.com/angular/angular/issues/23279#issuecomment-394129129

(I recommend read whole thread https://github.com/angular/angular/issues/23279 - i try something like this 
https://github.com/angular/angular/issues/23279#issuecomment-497213598)

But i recommend use this way (with provider) https://github.com/angular/angular/issues/23279#issuecomment-539435523. 

I use something similar on my other project - i read configuration in my SSR server.ts (and provide is for angular application through provider, but i also create workaround to read configuration through fetch() in browser main.ts.
